### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sosiristseng** [NTUMitoLab/jupyter-notebooks-source#1]
- [ ] Add Python notebooks
 - [ ] nbviewer link
 - [ ] Export conda environment for binder
 - [ ] Use Jupyter Book to build a website
